# Generated by Django 2.2.6 on 2019-10-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy_app', '0004_auto_20191021_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='join',
        ),
        migrations.AddField(
            model_name='trip',
            name='join',
            field=models.ManyToManyField(related_name='joiner', to='travel_buddy_app.User'),
        ),
    ]
